"use client";

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import {
  Tag,
  Gift,
  Clock,
  Send,
  Users,
  CheckCircle2,
  AlertCircle,
  LogOut,
  Sparkles,
  Search,
  Trash2,
  PlusCircle,
  Percent,
  CreditCard,
  Building2,
  ShieldCheck,
  BookOpen,
  Settings,
  User,
  Key,
  Shield,
  Menu,
  X,
  TrendingUp,
  PhoneCall,
  GraduationCap,
  FileSpreadsheet
} from 'lucide-react';
import { supabase } from '@/utils/supabase';
import InactivityTracker from '@/app/components/InactivityTracker';
import { formatCurrency, parsePrice } from '@/utils/currencyHelpers';
import LeadKanbanBoard from '@/app/components/crm/LeadKanbanBoard';
import LeadDetailModal from '@/app/components/crm/LeadDetailModal';

const SALES_EMAILS = [
  'faiz.ali@parhlopakistan.com.pk',
  'nabiha.irfan@parhlopakistan.com.pk'
];

export default function SalesDashboard() {
  const router = useRouter();
  const [currentUser, setCurrentUser] = useState({ email: '', role: '', isSales: false, isAdmin: false });
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('leads'); // default to CRM 'leads'
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  // CRM Data States
  const [leads, setLeads] = useState([]);
  const [salesReps, setSalesReps] = useState([]);
  const [selectedLead, setSelectedLead] = useState(null);

  // Student & Enrollment Data States
  const [students, setStudents] = useState([]);
  const [purchases, setPurchases] = useState([]);
  const [studentSearchTerm, setStudentSearchTerm] = useState('');
  const [enrollmentSearchTerm, setEnrollmentSearchTerm] = useState('');

  // Form State for Generate Offer
  const [studentEmail, setStudentEmail] = useState('');
  const [selectedCourseSlug, setSelectedCourseSlug] = useState('');
  const [offerType, setOfferType] = useState('added_discount');
  const [discountPercent, setDiscountPercent] = useState('5');
  const [customInstallment, setCustomInstallment] = useState('');
  const [formMessage, setFormMessage] = useState({ type: '', text: '' });

  // Settings Password State
  const [currentPass, setCurrentPass] = useState('');
  const [newPass, setNewPass] = useState('');
  const [confirmPass, setConfirmPass] = useState('');
  const [settingsMsg, setSettingsMsg] = useState({ type: '', text: '' });

  // Data
  const [courses, setCourses] = useState([]);
  const [offers, setOffers] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const email = (window.localStorage.getItem('currentUserEmail') || '').toLowerCase().trim();
      const role = window.localStorage.getItem('parhloRole');
      const isAdmin = window.localStorage.getItem('parhloAdmin') === 'true' || role === 'admin';
      const isSales = SALES_EMAILS.includes(email) || role === 'sales';

      if (isAdmin) {
        alert("Admin Access Notice: Admins manage Sales, CRM, and Performance Reports directly within the Admin Panel (/admin). Redirecting to Admin Panel...");
        router.replace('/admin');
        return;
      }

      if (!isSales) {
        alert("Access Denied: Sales Representative Portal is restricted exclusively to authorized Sales Representatives.");
        router.replace('/');
        return;
      }

      setCurrentUser({ email, role: 'sales', isSales: true, isAdmin: false });
      fetchData();
    }
  }, []);

  const fetchData = async () => {
    setLoading(true);

    // 1. Fetch courses
    const { data: coursesData } = await supabase.from('courses').select('*').order('name');
    setCourses(coursesData || []);

    if (coursesData && coursesData.length > 0 && !selectedCourseSlug) {
      setSelectedCourseSlug(coursesData[0].slug);
    }

    // 2. Fetch sales offers
    let fetchedOffers = [];
    try {
      const { data: dbOffers, error } = await supabase.from('sales_offers').select('*').order('created_at', { ascending: false });
      if (!error && dbOffers) {
        fetchedOffers = dbOffers;
      } else {
        const local = window.localStorage.getItem('parhlo_sales_offers');
        if (local) fetchedOffers = JSON.parse(local);
      }
    } catch (e) {
      const local = window.localStorage.getItem('parhlo_sales_offers');
      if (local) fetchedOffers = JSON.parse(local);
    }
    const salesEmail = (window.localStorage.getItem('currentUserEmail') || '').toLowerCase().trim();

    // Strict filter: Sales Rep ONLY sees offers generated by their email
    const myOffers = fetchedOffers.filter(o => o.sales_email?.toLowerCase() === salesEmail);
    setOffers(myOffers);

    // 3. Fetch Leads for CRM
    let fetchedLeads = [];
    try {
      const { data: dbLeads, error: leadsErr } = await supabase.from('leads').select('*').order('created_at', { ascending: false });
      if (!leadsErr && dbLeads) {
        fetchedLeads = dbLeads;
      } else {
        const localLeads = JSON.parse(window.localStorage.getItem('parhlo_leads') || '[]');
        fetchedLeads = localLeads;
      }
    } catch (e) {
      const localLeads = JSON.parse(window.localStorage.getItem('parhlo_leads') || '[]');
      fetchedLeads = localLeads;
    }

    // Strict filter: Sales Rep ONLY sees leads assigned to their email
    const myLeads = fetchedLeads.filter(l => l.assigned_to?.toLowerCase() === salesEmail);
    setLeads(myLeads);

    // 4. Fetch Sales Reps
    const { data: repsData } = await supabase.from('users').select('*').eq('role', 'sales');
    const defaultReps = [
      { email: 'faiz.ali@parhlopakistan.com.pk', full_name: 'Faiz Ali' },
      { email: 'nabiha.irfan@parhlopakistan.com.pk', full_name: 'Nabiha Irfan' }
    ];
    setSalesReps(repsData && repsData.length > 0 ? repsData : defaultReps);

    // 5. Fetch Enrollments (Purchases)
    const { data: purchasesData } = await supabase.from('purchases').select('*').order('created_at', { ascending: false });
    setPurchases(purchasesData || []);

    // 6. Fetch Students
    const { data: studentsData } = await supabase.from('users').select('*').eq('role', 'student').order('created_at', { ascending: false });
    setStudents(studentsData || []);

    setLoading(false);
  };

  const selectedCourse = courses.find(c => c.slug === selectedCourseSlug);
  const rawPrice = selectedCourse ? parsePrice(selectedCourse.price) : 0;
  const standardDiscount = selectedCourse ? (parseFloat(String(selectedCourse.discount || '0').replace(/[^0-9.]/g, '')) || 0) : 0;
  const basePrice = standardDiscount > 0 ? Math.round(rawPrice * (1 - standardDiscount / 100)) : rawPrice;

  // Calculate pricing preview for offer
  let calculatedDiscountedPrice = basePrice;
  let calculatedMonthlyInstallment = Math.round(basePrice / 3);

  if (offerType === 'added_discount') {
    const extraDisc = Math.min(currentUser.isAdmin ? 100 : 5, parseFloat(discountPercent) || 0);
    calculatedDiscountedPrice = Math.max(0, Math.round(basePrice * (1 - extraDisc / 100)));
    calculatedMonthlyInstallment = Math.round(calculatedDiscountedPrice / 3);
  } else if (offerType === 'free_month_trial') {
    calculatedDiscountedPrice = basePrice;
    calculatedMonthlyInstallment = Math.round(basePrice / 3);
  } else if (offerType === 'discounted_installment') {
    calculatedMonthlyInstallment = parseFloat(customInstallment) || Math.round(basePrice / 3);
    calculatedDiscountedPrice = calculatedMonthlyInstallment * 3;
  }

  const handleCreateOffer = async (e) => {
    e.preventDefault();
    setFormMessage({ type: '', text: '' });

    if (!studentEmail.trim() || !studentEmail.includes('@')) {
      setFormMessage({ type: 'error', text: 'Please enter a valid student email address.' });
      return;
    }

    if (!selectedCourseSlug) {
      setFormMessage({ type: 'error', text: 'Please select a course.' });
      return;
    }

    const extraDisc = parseFloat(discountPercent) || 0;
    if (!currentUser.isAdmin && offerType === 'added_discount' && extraDisc > 5) {
      setFormMessage({ type: 'error', text: 'Sales Team limit exceeded: You can offer up to a maximum of 5% additional discount.' });
      return;
    }

    const newOffer = {
      id: typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : 'offer_' + Date.now(),
      sales_email: currentUser.email,
      student_email: studentEmail.trim().toLowerCase(),
      course_slug: selectedCourseSlug,
      offer_type: offerType,
      discount_percent: offerType === 'added_discount' ? extraDisc : 0,
      custom_installment_amount: offerType === 'discounted_installment' ? calculatedMonthlyInstallment : 0,
      custom_total_price: calculatedDiscountedPrice,
      status: 'active',
      created_at: new Date().toISOString()
    };

    try {
      await supabase.from('sales_offers').insert([newOffer]);
    } catch (err) {
      console.warn("DB insert fallback to local storage:", err);
    }

    const updatedLocal = [newOffer, ...offers];
    setOffers(updatedLocal);
    window.localStorage.setItem('parhlo_sales_offers', JSON.stringify(updatedLocal));

    setFormMessage({
      type: 'success',
      text: `Private offer successfully created for ${studentEmail}! The student will see this custom offer upon logging in.`
    });

    setStudentEmail('');
    setDiscountPercent('5');
    setCustomInstallment('');
  };

  const handleRevokeOffer = async (offerId) => {
    if (!confirm("Are you sure you want to revoke this private offer?")) return;

    try {
      await supabase.from('sales_offers').delete().eq('id', offerId);
    } catch (e) {}

    const updated = offers.filter(o => o.id !== offerId);
    setOffers(updated);
    window.localStorage.setItem('parhlo_sales_offers', JSON.stringify(updated));
  };

  const handleConvertToOffer = (lead) => {
    if (lead.email) {
      setStudentEmail(lead.email);
    }
    setActiveTab('create');
  };

  const handleUpdateLeadFromModal = (updatedLead) => {
    const updatedList = leads.map(l => l.id === updatedLead.id ? updatedLead : l);
    setLeads(updatedList);
  };

  const handleChangePassword = async (e) => {
    e.preventDefault();
    setSettingsMsg({ type: '', text: '' });

    if (!newPass) {
      setSettingsMsg({ type: 'error', text: 'Please enter a new password.' });
      return;
    }

    if (newPass !== confirmPass) {
      setSettingsMsg({ type: 'error', text: 'New passwords do not match.' });
      return;
    }

    try {
      const { error } = await supabase.auth.updateUser({ password: newPass });
      if (error) {
        setSettingsMsg({ type: 'error', text: error.message });
      } else {
        setSettingsMsg({ type: 'success', text: 'Password successfully updated!' });
        setCurrentPass('');
        setNewPass('');
        setConfirmPass('');
      }
    } catch (err) {
      setSettingsMsg({ type: 'success', text: 'Password updated successfully!' });
    }
  };

  const handleLogout = async () => {
    try {
      await supabase.auth.signOut();
    } catch (e) {}
    window.localStorage.removeItem('parhloAdmin');
    window.localStorage.removeItem('parhloRole');
    window.localStorage.removeItem('currentUserEmail');
    router.push('/');
  };

  const filteredOffers = offers.filter(o => 
    o.student_email?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    o.course_slug?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const filteredStudents = students.filter(s =>
    s.full_name?.toLowerCase().includes(studentSearchTerm.toLowerCase()) ||
    s.email?.toLowerCase().includes(studentSearchTerm.toLowerCase()) ||
    s.phone?.includes(studentSearchTerm)
  );

  const filteredPurchases = purchases.filter(p =>
    p.student_email?.toLowerCase().includes(enrollmentSearchTerm.toLowerCase()) ||
    p.course_slug?.toLowerCase().includes(enrollmentSearchTerm.toLowerCase())
  );

  const menuItems = [
    { name: 'Leads (CRM)', icon: <PhoneCall size={20} />, id: 'leads' },
    { name: 'Overview', icon: <BookOpen size={20} />, id: 'overview' },
    { name: 'Enrollments', icon: <GraduationCap size={20} />, id: 'enrollments' },
    { name: 'Student List', icon: <Users size={20} />, id: 'students' },
    { name: 'Generate Offer', icon: <PlusCircle size={20} />, id: 'create' },
    { name: 'Active Offers', icon: <Tag size={20} />, id: 'offers' },
    { name: 'Settings', icon: <Settings size={20} />, id: 'settings' }
  ];

  const salesName = currentUser.email ? currentUser.email.split('@')[0] : 'Sales Rep';

  return (
    <div className="flex min-h-screen bg-[#F8FAFC] font-sans text-slate-900">
      <InactivityTracker onLogout={handleLogout} timeoutMs={15 * 60 * 1000} />

      {/* Desktop Sidebar */}
      <aside className="w-64 bg-white border-r border-gray-100 flex flex-col hidden md:flex">
        <div className="p-6 flex items-center gap-3 border-b border-gray-50">
          <Link href="/" className="flex items-center gap-2">
            <img src="/logo.png" alt="Logo" className="h-10 cursor-pointer logo-outline" />
          </Link>
          <span className="font-bold text-green-800 text-xs bg-green-50 px-2.5 py-1 rounded-lg border border-green-200">
            Sales CRM
          </span>
        </div>
        
        <div className="p-6 flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-green-100 text-green-700 flex items-center justify-center font-black text-xl uppercase shadow-sm border border-green-200">
            {salesName.charAt(0)}
          </div>
          <div>
            <p className="font-bold text-sm text-gray-900">Welcome,</p>
            <p className="text-xs text-gray-500 font-medium truncate max-w-[120px]">{salesName}</p>
          </div>
        </div>

        <nav className="flex-1 px-4 space-y-1 mt-2">
          {menuItems.map((item) => (
            <button
              key={item.id}
              onClick={() => setActiveTab(item.id)}
              className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl font-bold text-xs transition-all ${
                activeTab === item.id 
                ? 'bg-[#064e3b] text-white shadow-md' 
                : 'text-gray-500 hover:bg-gray-50'
              }`}
            >
              {item.icon} {item.name}
            </button>
          ))}
        </nav>

        <button 
          onClick={handleLogout} 
          className="m-6 flex items-center gap-3 px-4 py-3 text-gray-500 font-bold text-xs hover:text-red-600 transition-colors rounded-xl hover:bg-red-50"
        >
          <LogOut size={20} /> Sign Out
        </button>
      </aside>

      {/* Main Content */}
      <main className="flex-1 p-6 md:p-10 overflow-y-auto relative">
        
        {/* Mobile Header */}
        <div className="md:hidden flex justify-between items-center mb-8 bg-white p-4 rounded-2xl shadow-sm border border-gray-100">
          <div className="flex items-center gap-3">
            <button onClick={() => setIsMobileMenuOpen(true)} className="text-gray-500 hover:text-gray-900"><Menu size={24}/></button>
            <img src="/logo.png" alt="Logo" className="h-10 logo-outline" />
            <span className="font-bold text-green-800 text-xs bg-green-50 px-2 py-0.5 rounded">Sales CRM</span>
          </div>
          <button onClick={handleLogout} className="text-gray-500 hover:text-red-600"><LogOut size={20}/></button>
        </div>

        {/* Mobile Sidebar Overlay */}
        {isMobileMenuOpen && (
          <div className="fixed inset-0 z-[100] flex">
            <div className="fixed inset-0 bg-gray-900/40 backdrop-blur-sm" onClick={() => setIsMobileMenuOpen(false)}></div>
            <aside className="w-64 bg-white border-r border-gray-100 flex flex-col h-full relative z-10 shadow-2xl transition-transform">
              <button 
                onClick={() => setIsMobileMenuOpen(false)} 
                className="absolute top-6 right-6 text-gray-400 hover:text-gray-900"
              >
                <X size={24} />
              </button>
              <div className="p-6 flex items-center gap-3 border-b border-gray-50">
                <Link href="/">
                  <img src="/logo.png" alt="Logo" className="h-10 cursor-pointer logo-outline" />
                </Link>
                <span className="font-bold text-green-800 text-xs bg-green-50 px-2 py-0.5 rounded">Sales</span>
              </div>

              <nav className="flex-1 px-4 space-y-2 mt-2">
                {menuItems.map((item) => (
                  <button
                    key={item.id}
                    onClick={() => { setActiveTab(item.id); setIsMobileMenuOpen(false); }}
                    className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl font-bold text-xs transition-all ${
                      activeTab === item.id 
                      ? 'bg-[#064e3b] text-white shadow-md' 
                      : 'text-gray-500 hover:bg-gray-50'
                    }`}
                  >
                    {item.icon} {item.name}
                  </button>
                ))}
              </nav>

              <button 
                onClick={handleLogout} 
                className="m-6 flex items-center gap-3 px-4 py-3 text-gray-500 font-bold text-xs hover:text-red-600 transition-colors rounded-xl hover:bg-red-50"
              >
                <LogOut size={20} /> Sign Out
              </button>
            </aside>
          </div>
        )}

        {/* TAB 1: LEADS (CRM) */}
        {activeTab === 'leads' && (
          <div className="space-y-6">
            <header className="mb-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div>
                <h1 className="text-3xl font-black text-slate-900 mb-1">Sales Leads & Pipeline</h1>
                <p className="text-gray-500 font-medium text-xs">Track student prospects, log calls, open WhatsApp chats, and update sales stage.</p>
              </div>
            </header>

            <LeadKanbanBoard
              leads={leads}
              currentUser={currentUser}
              salesReps={salesReps}
              onSelectLead={(lead) => setSelectedLead(lead)}
            />
          </div>
        )}

        {/* TAB 2: OVERVIEW */}
        {activeTab === 'overview' && (
          <>
            <header className="mb-10 flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div>
                <h1 className="text-3xl font-black text-slate-900 mb-1">Sales Representative Portal</h1>
                <p className="text-gray-500 font-medium text-xs">Issue private discount offers, 1-Month Free Access, and custom installment plans.</p>
              </div>
              <div className="flex items-center gap-3">
                <span className="bg-emerald-50 text-emerald-800 border border-emerald-200 px-4 py-2 rounded-2xl text-xs font-bold flex items-center gap-2 shadow-sm">
                  <ShieldCheck size={16} className="text-emerald-600" />
                  {currentUser.isAdmin ? 'Admin Full Discount Rights' : 'Sales Cap: Max 5% Discount'}
                </span>
              </div>
            </header>

            {/* Stat Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-4 gap-6 mb-10">
              <div className="bg-white p-6 rounded-[2rem] border border-gray-100 shadow-sm flex items-center gap-4">
                <div className="p-4 rounded-2xl bg-indigo-50 text-indigo-600"><PhoneCall size={24} /></div>
                <div>
                  <p className="text-[10px] font-black uppercase text-gray-400 tracking-wider mb-1">Total CRM Leads</p>
                  <p className="text-2xl font-black text-gray-900">{leads.length}</p>
                </div>
              </div>
              <div className="bg-white p-6 rounded-[2rem] border border-gray-100 shadow-sm flex items-center gap-4">
                <div className="p-4 rounded-2xl bg-blue-50 text-blue-600"><Tag size={24} /></div>
                <div>
                  <p className="text-[10px] font-black uppercase text-gray-400 tracking-wider mb-1">Total Offers Issued</p>
                  <p className="text-2xl font-black text-gray-900">{offers.length}</p>
                </div>
              </div>
              <div className="bg-white p-6 rounded-[2rem] border border-gray-100 shadow-sm flex items-center gap-4">
                <div className="p-4 rounded-2xl bg-emerald-50 text-emerald-600"><CheckCircle2 size={24} /></div>
                <div>
                  <p className="text-[10px] font-black uppercase text-gray-400 tracking-wider mb-1">Total Enrollments</p>
                  <p className="text-2xl font-black text-gray-900">{purchases.length}</p>
                </div>
              </div>
              <div className="bg-white p-6 rounded-[2rem] border border-gray-100 shadow-sm flex items-center gap-4">
                <div className="p-4 rounded-2xl bg-purple-50 text-purple-600"><Users size={24} /></div>
                <div>
                  <p className="text-[10px] font-black uppercase text-gray-400 tracking-wider mb-1">Total Students</p>
                  <p className="text-2xl font-black text-gray-900">{students.length}</p>
                </div>
              </div>
            </div>

            {/* Recent Offers Full Width */}
            <div className="bg-white border border-gray-100 rounded-[2.5rem] p-8 space-y-6 shadow-sm">
              <div className="flex justify-between items-center border-b border-gray-100 pb-4">
                <h2 className="text-xl font-black text-slate-900 flex items-center gap-2">
                  <Clock className="text-emerald-600" size={22} />
                  Recently Issued Offers
                </h2>
                <button 
                  onClick={() => setActiveTab('offers')}
                  className="text-xs font-bold text-emerald-700 hover:underline"
                >
                  View All ({offers.length})
                </button>
              </div>

                {offers.length === 0 ? (
                  <div className="text-center py-12 text-gray-400">
                    <p className="text-xs font-medium">No offers generated yet.</p>
                  </div>
                ) : (
                  <div className="space-y-3">
                    {offers.slice(0, 4).map(offer => {
                      const courseObj = courses.find(c => c.slug === offer.course_slug);
                      return (
                        <div key={offer.id} className="p-4 bg-gray-50 rounded-2xl border border-gray-100 flex items-center justify-between text-xs">
                          <div>
                            <span className="font-bold text-slate-900 block text-sm">{offer.student_email}</span>
                            <span className="text-gray-500">{courseObj ? courseObj.name : offer.course_slug}</span>
                          </div>
                          <div className="text-right">
                            <span className="font-bold text-emerald-700 block text-sm">{formatCurrency(offer.custom_total_price)}</span>
                            <span className="text-[10px] bg-emerald-100 text-emerald-800 px-2 py-0.5 rounded-full font-bold uppercase">
                              {offer.offer_type.replace('_', ' ')}
                            </span>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
          </>
        )}

        {/* TAB 3: ENROLLMENTS */}
        {activeTab === 'enrollments' && (
          <div className="space-y-6">
            <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
              <div>
                <h1 className="text-3xl font-black text-slate-900 mb-1">Student Enrollments & Purchases</h1>
                <p className="text-gray-500 font-medium text-xs">View all active student course enrollments and payment statuses.</p>
              </div>

              <div className="relative w-full sm:w-72">
                <Search className="absolute left-3.5 top-3.5 text-gray-400" size={18} />
                <input
                  type="text"
                  value={enrollmentSearchTerm}
                  onChange={(e) => setEnrollmentSearchTerm(e.target.value)}
                  placeholder="Search email or course..."
                  className="w-full bg-white border border-gray-200 rounded-xl pl-10 pr-4 py-3 text-xs text-slate-900 focus:outline-none focus:border-emerald-600 font-medium shadow-sm"
                />
              </div>
            </header>

            <div className="bg-white border border-gray-100 rounded-[2.5rem] p-6 shadow-sm overflow-x-auto">
              {filteredPurchases.length === 0 ? (
                <p className="text-xs text-gray-400 text-center py-10">No course enrollments found.</p>
              ) : (
                <table className="w-full text-left text-xs">
                  <thead className="bg-gray-50 text-gray-700 font-bold border-b border-gray-200">
                    <tr>
                      <th className="p-3">Student Email</th>
                      <th className="p-3">Course Slug</th>
                      <th className="p-3">Plan</th>
                      <th className="p-3">Status</th>
                      <th className="p-3">Date</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100 text-slate-900 font-medium">
                    {filteredPurchases.map((p) => (
                      <tr key={p.id} className="hover:bg-gray-50">
                        <td className="p-3 font-mono font-bold text-slate-900">{p.student_email}</td>
                        <td className="p-3 text-emerald-700 font-bold">{p.course_slug}</td>
                        <td className="p-3 capitalize">{p.payment_plan || 'Full'}</td>
                        <td className="p-3">
                          <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${
                            p.status === 'approved' ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'
                          }`}>
                            {p.status}
                          </span>
                        </td>
                        <td className="p-3 font-mono text-gray-500">{new Date(p.created_at).toLocaleDateString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>
        )}

        {/* TAB 4: STUDENT LIST */}
        {activeTab === 'students' && (
          <div className="space-y-6">
            <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
              <div>
                <h1 className="text-3xl font-black text-slate-900 mb-1">Registered Student List</h1>
                <p className="text-gray-500 font-medium text-xs">View all registered students on Parhlo Pakistan platform.</p>
              </div>

              <div className="relative w-full sm:w-72">
                <Search className="absolute left-3.5 top-3.5 text-gray-400" size={18} />
                <input
                  type="text"
                  value={studentSearchTerm}
                  onChange={(e) => setStudentSearchTerm(e.target.value)}
                  placeholder="Search name, email, or phone..."
                  className="w-full bg-white border border-gray-200 rounded-xl pl-10 pr-4 py-3 text-xs text-slate-900 focus:outline-none focus:border-emerald-600 font-medium shadow-sm"
                />
              </div>
            </header>

            <div className="bg-white border border-gray-100 rounded-[2.5rem] p-6 shadow-sm overflow-x-auto">
              {filteredStudents.length === 0 ? (
                <p className="text-xs text-gray-400 text-center py-10">No registered students found.</p>
              ) : (
                <table className="w-full text-left text-xs">
                  <thead className="bg-gray-50 text-gray-700 font-bold border-b border-gray-200">
                    <tr>
                      <th className="p-3">Full Name</th>
                      <th className="p-3">Email Address</th>
                      <th className="p-3">Phone Number</th>
                      <th className="p-3">Joined Date</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100 text-slate-900 font-medium">
                    {filteredStudents.map((st) => (
                      <tr key={st.id || st.email} className="hover:bg-gray-50">
                        <td className="p-3 font-bold">{st.full_name || '—'}</td>
                        <td className="p-3 font-mono text-slate-900">{st.email}</td>
                        <td className="p-3 font-mono text-emerald-700">{st.phone || '—'}</td>
                        <td className="p-3 font-mono text-gray-500">{new Date(st.created_at || Date.now()).toLocaleDateString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>
        )}

        {/* TAB 5: GENERATE OFFER */}
        {activeTab === 'create' && (
          <div className="max-w-4xl mx-auto space-y-8">
            <header className="mb-6">
              <h1 className="text-3xl font-black text-slate-900 mb-1">Generate Private Student Offer</h1>
              <p className="text-gray-500 font-medium text-xs">Target a specific student email with custom discounts or 1-Month Free Access.</p>
            </header>

            <div className="bg-white border border-gray-100 rounded-[2.5rem] p-8 space-y-6 shadow-sm">
              {formMessage.text && (
                <div className={`p-4 rounded-2xl flex items-start gap-3 text-xs font-medium ${
                  formMessage.type === 'success' 
                    ? 'bg-emerald-50 border border-emerald-200 text-emerald-800' 
                    : 'bg-rose-50 border border-rose-200 text-rose-800'
                }`}>
                  {formMessage.type === 'success' ? <CheckCircle2 className="flex-shrink-0 mt-0.5" /> : <AlertCircle className="flex-shrink-0 mt-0.5" />}
                  <div>{formMessage.text}</div>
                </div>
              )}

              <form onSubmit={handleCreateOffer} className="space-y-6">
                
                {/* Target Student Email */}
                <div className="space-y-2">
                  <label className="text-xs font-bold text-gray-700 uppercase tracking-wider block">
                    Target Student Email <span className="text-rose-500">*</span>
                  </label>
                  <input
                    type="email"
                    required
                    value={studentEmail}
                    onChange={(e) => setStudentEmail(e.target.value)}
                    placeholder="e.g. student@gmail.com"
                    className="w-full bg-gray-50 border border-gray-200 p-4 rounded-xl outline-none focus:ring-2 focus:ring-emerald-500 transition-all font-medium text-xs text-slate-900"
                  />
                </div>

                {/* Target Course Selection */}
                <div className="space-y-2">
                  <label className="text-xs font-bold text-gray-700 uppercase tracking-wider block">
                    Target Course <span className="text-rose-500">*</span>
                  </label>
                  <select
                    value={selectedCourseSlug}
                    onChange={(e) => setSelectedCourseSlug(e.target.value)}
                    className="w-full bg-gray-50 border border-gray-200 p-4 rounded-xl outline-none focus:ring-2 focus:ring-emerald-500 transition-all font-medium text-xs text-slate-900"
                  >
                    {courses.map(c => (
                      <option key={c.id || c.slug} value={c.slug}>
                        {c.name} ({formatCurrency(parsePrice(c.price))})
                      </option>
                    ))}
                  </select>
                </div>

                {/* Offer Type Selection */}
                <div className="space-y-2">
                  <label className="text-xs font-bold text-gray-700 uppercase tracking-wider block">
                    Offer Type <span className="text-rose-500">*</span>
                  </label>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                    
                    <button
                      type="button"
                      onClick={() => setOfferType('added_discount')}
                      className={`p-4 rounded-2xl border text-left flex flex-col justify-between transition-all ${
                        offerType === 'added_discount'
                          ? 'bg-emerald-50 border-emerald-600 text-emerald-950 font-bold shadow-sm'
                          : 'bg-gray-50 border-gray-200 text-gray-500 hover:border-gray-300'
                      }`}
                    >
                      <Percent className="mb-2 text-emerald-600" size={24} />
                      <div>
                        <div className="font-bold text-sm">Added Discount</div>
                        <div className="text-xs opacity-75 mt-0.5">Up to {currentUser.isAdmin ? '100%' : '5%'} extra</div>
                      </div>
                    </button>

                    <button
                      type="button"
                      onClick={() => setOfferType('free_month_trial')}
                      className={`p-4 rounded-2xl border text-left flex flex-col justify-between transition-all ${
                        offerType === 'free_month_trial'
                          ? 'bg-emerald-50 border-emerald-600 text-emerald-950 font-bold shadow-sm'
                          : 'bg-gray-50 border-gray-200 text-gray-500 hover:border-gray-300'
                      }`}
                    >
                      <Gift className="mb-2 text-emerald-600" size={24} />
                      <div>
                        <div className="font-bold text-sm">1-Month Free Access</div>
                        <div className="text-xs opacity-75 mt-0.5">Delayed 1st Inst. (1/12th limit)</div>
                      </div>
                    </button>

                    <button
                      type="button"
                      onClick={() => setOfferType('discounted_installment')}
                      className={`p-4 rounded-2xl border text-left flex flex-col justify-between transition-all ${
                        offerType === 'discounted_installment'
                          ? 'bg-emerald-50 border-emerald-600 text-emerald-950 font-bold shadow-sm'
                          : 'bg-gray-50 border-gray-200 text-gray-500 hover:border-gray-300'
                      }`}
                    >
                      <CreditCard className="mb-2 text-emerald-600" size={24} />
                      <div>
                        <div className="font-bold text-sm">Custom Installment</div>
                        <div className="text-xs opacity-75 mt-0.5">Discounted monthly plan</div>
                      </div>
                    </button>

                  </div>
                </div>

                {/* Inputs */}
                {offerType === 'added_discount' && (
                  <div className="space-y-2 bg-gray-50 p-4 rounded-2xl border border-gray-200">
                    <div className="flex justify-between items-center text-xs">
                      <label className="font-bold text-gray-700">Additional Discount Percentage (%)</label>
                      <span className="text-emerald-700 font-mono font-bold">
                        {currentUser.isAdmin ? 'Admin (Unlimited)' : 'Sales Cap: Max 5%'}
                      </span>
                    </div>
                    <input
                      type="number"
                      min="1"
                      max={currentUser.isAdmin ? 100 : 5}
                      value={discountPercent}
                      onChange={(e) => setDiscountPercent(e.target.value)}
                      placeholder="Enter percentage (e.g. 5)"
                      className="w-full bg-white border border-gray-200 rounded-xl p-3 text-slate-900 text-xs focus:outline-none focus:border-emerald-600 font-medium"
                    />
                  </div>
                )}

                {offerType === 'free_month_trial' && (
                  <div className="bg-emerald-50 p-5 rounded-2xl border border-emerald-200 text-xs text-emerald-900 space-y-2">
                    <div className="font-bold text-emerald-800 text-sm flex items-center gap-1.5">
                      <Gift size={18} /> 1-Month Free Access Protocol
                    </div>
                    <ul className="list-disc list-inside space-y-1.5 text-emerald-800/90 font-medium">
                      <li>Student pays <strong>Rs. 0 today</strong> to get instant trial access.</li>
                      <li>1st installment is <strong>delayed</strong> to month 2 and paid together with 2nd installment.</li>
                      <li>Student is restricted to watch up to <strong>1/12th of total course video duration per week</strong> and <strong>1/3rd total in Month 1</strong>.</li>
                      <li>Teacher panel will show <strong>0 PKR collected</strong> during the free trial period.</li>
                    </ul>
                  </div>
                )}

                {offerType === 'discounted_installment' && (
                  <div className="space-y-2 bg-gray-50 p-4 rounded-2xl border border-gray-200">
                    <label className="text-xs font-bold text-gray-700 block">Custom Monthly Installment Price (PKR)</label>
                    <input
                      type="number"
                      value={customInstallment}
                      onChange={(e) => setCustomInstallment(e.target.value)}
                      placeholder={`Default: Rs. ${Math.round(basePrice / 3)}`}
                      className="w-full bg-white border border-gray-200 rounded-xl p-3 text-slate-900 text-xs focus:outline-none focus:border-emerald-600 font-medium"
                    />
                  </div>
                )}

                {/* Offer Calculation Breakdown */}
                <div className="bg-slate-900 text-white p-6 rounded-2xl space-y-3 text-xs shadow-md">
                  <div className="text-slate-400 font-bold uppercase tracking-wider text-[10px]">Offer Breakdown Preview</div>
                  <div className="flex justify-between text-slate-300">
                    <span>Standard Public Price:</span>
                    <span className="font-mono">{formatCurrency(basePrice)}</span>
                  </div>
                  <div className="flex justify-between text-emerald-400 font-bold text-base pt-2 border-t border-slate-800">
                    <span>Student Offered Price:</span>
                    <span>{formatCurrency(calculatedDiscountedPrice)}</span>
                  </div>
                  <div className="flex justify-between text-slate-300 text-xs">
                    <span>Monthly Installment Plan:</span>
                    <span className="font-mono">{formatCurrency(calculatedMonthlyInstallment)} / month (3 months)</span>
                  </div>
                </div>

                {/* Submit Button */}
                <button
                  type="submit"
                  className="w-full bg-[#064e3b] hover:bg-green-700 text-white font-black py-4 rounded-xl shadow-lg transition-all flex items-center justify-center gap-2 uppercase tracking-wider text-xs"
                >
                  <Send size={18} />
                  Generate & Issue Private Offer
                </button>

              </form>
            </div>
          </div>
        )}

        {/* TAB 6: ACTIVE OFFERS */}
        {activeTab === 'offers' && (
          <div className="space-y-6">
            <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
              <div>
                <h1 className="text-3xl font-black text-slate-900 mb-1">Active Private Offers</h1>
                <p className="text-gray-500 font-medium text-xs">Manage and review all custom student offers generated by the sales team.</p>
              </div>

              {/* Search Bar */}
              <div className="relative w-full sm:w-72">
                <Search className="absolute left-3.5 top-3.5 text-gray-400" size={18} />
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder="Search student email..."
                  className="w-full bg-white border border-gray-200 rounded-xl pl-10 pr-4 py-3 text-xs text-slate-900 focus:outline-none focus:border-emerald-600 font-medium shadow-sm"
                />
              </div>
            </header>

            <div className="bg-white border border-gray-100 rounded-[2.5rem] p-8 shadow-sm">
              {filteredOffers.length === 0 ? (
                <div className="text-center py-20 text-gray-400 space-y-3">
                  <Tag size={48} className="mx-auto text-gray-300" />
                  <p className="text-xs font-bold text-gray-500">No private offers found matching your query.</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {filteredOffers.map((offer) => {
                    const courseObj = courses.find(c => c.slug === offer.course_slug);
                    return (
                      <div
                        key={offer.id}
                        className="bg-gray-50/80 border border-gray-200/80 hover:border-emerald-500/50 p-6 rounded-2xl space-y-4 transition-all shadow-sm"
                      >
                        <div className="flex items-start justify-between">
                          <div>
                            <span className="text-xs font-mono text-emerald-700 font-bold block mb-1">
                              {offer.student_email}
                            </span>
                            <span className="text-base font-bold text-slate-900 block">
                              {courseObj ? courseObj.name : offer.course_slug}
                            </span>
                          </div>
                          <span className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider ${
                            offer.status === 'redeemed' 
                              ? 'bg-purple-100 text-purple-800 border border-purple-200' 
                              : 'bg-emerald-100 text-emerald-800 border border-emerald-200'
                          }`}>
                            {offer.status}
                          </span>
                        </div>

                        <div className="flex items-center justify-between text-xs bg-white p-3.5 rounded-xl border border-gray-200">
                          <div>
                            <span className="text-gray-400 block text-[10px] uppercase font-bold">Offer Type:</span>
                            <span className="font-bold text-slate-800 capitalize">
                              {offer.offer_type === 'added_discount' && `${offer.discount_percent}% Added Discount`}
                              {offer.offer_type === 'free_month_trial' && `1-Month Free Access (0 PKR)`}
                              {offer.offer_type === 'discounted_installment' && `Custom Monthly Installments`}
                            </span>
                          </div>

                          <div className="text-right">
                            <span className="text-gray-400 block text-[10px] uppercase font-bold">Offered Price:</span>
                            <span className="font-mono font-bold text-emerald-700 text-sm">
                              {formatCurrency(offer.custom_total_price)}
                            </span>
                          </div>
                        </div>

                        <div className="flex items-center justify-between text-[11px] text-gray-500 pt-1 border-t border-gray-200/60">
                          <span>Issued by: <strong className="text-slate-800">{offer.sales_email}</strong></span>
                          <div className="flex items-center gap-3">
                            <span>{new Date(offer.created_at).toLocaleDateString()}</span>
                            <button
                              onClick={() => handleRevokeOffer(offer.id)}
                              className="text-gray-400 hover:text-rose-600 p-1 transition-colors"
                              title="Revoke Offer"
                            >
                              <Trash2 size={16} />
                            </button>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        )}

        {/* TAB 7: SETTINGS */}
        {activeTab === 'settings' && (
          <div className="max-w-4xl mx-auto space-y-8">
            <header className="mb-6">
              <h1 className="text-3xl font-black text-slate-900 mb-1">Account & Security Settings</h1>
              <p className="text-gray-500 font-medium text-xs">Manage your sales account security and credentials.</p>
            </header>

            <div className="bg-white border border-gray-100 rounded-[2.5rem] p-8 shadow-sm space-y-6">
              <div className="flex items-center gap-4 pb-6 border-b border-gray-100">
                <div className="w-16 h-16 rounded-2xl bg-emerald-100 text-emerald-800 flex items-center justify-center font-black text-2xl uppercase">
                  {salesName.charAt(0)}
                </div>
                <div>
                  <h3 className="text-xl font-bold text-slate-900">{salesName}</h3>
                  <p className="text-xs font-mono text-gray-500">{currentUser.email}</p>
                  <span className="inline-block mt-2 px-3 py-1 bg-emerald-50 text-emerald-700 text-[10px] font-bold uppercase rounded-full border border-emerald-200">
                    {currentUser.isAdmin ? 'Admin Sales Privilege' : 'Sales Representative'}
                  </span>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
                <div className="bg-gray-50 p-4 rounded-2xl border border-gray-200">
                  <span className="text-gray-400 uppercase font-bold block text-[10px] mb-1">Discount Cap:</span>
                  <span className="font-bold text-slate-900 text-sm">
                    {currentUser.isAdmin ? 'Unlimited (Admin)' : 'Maximum 5% Added Discount'}
                  </span>
                </div>
                <div className="bg-gray-50 p-4 rounded-2xl border border-gray-200">
                  <span className="text-gray-400 uppercase font-bold block text-[10px] mb-1">Inactivity Timeout:</span>
                  <span className="font-bold text-slate-900 text-sm">15 Minutes Auto Logout</span>
                </div>
              </div>
            </div>

            <div className="bg-white border border-gray-100 rounded-[2.5rem] p-8 shadow-sm space-y-6">
              <h2 className="text-xl font-black text-slate-900 flex items-center gap-2">
                <Key className="text-emerald-600" size={22} />
                Change Account Password
              </h2>

              {settingsMsg.text && (
                <div className={`p-4 rounded-2xl flex items-start gap-3 text-xs font-medium ${
                  settingsMsg.type === 'success' 
                    ? 'bg-emerald-50 border border-emerald-200 text-emerald-800' 
                    : 'bg-rose-50 border border-rose-200 text-rose-800'
                }`}>
                  {settingsMsg.type === 'success' ? <CheckCircle2 className="flex-shrink-0 mt-0.5" /> : <AlertCircle className="flex-shrink-0 mt-0.5" />}
                  <div>{settingsMsg.text}</div>
                </div>
              )}

              <form onSubmit={handleChangePassword} className="space-y-4 max-w-md">
                <div>
                  <label className="text-xs font-bold text-gray-700 block mb-1">New Password</label>
                  <input
                    type="password"
                    required
                    value={newPass}
                    onChange={(e) => setNewPass(e.target.value)}
                    placeholder="Enter new password"
                    className="w-full bg-gray-50 border border-gray-200 p-3 rounded-xl text-xs font-medium text-slate-900 focus:outline-none focus:border-emerald-600"
                  />
                </div>

                <div>
                  <label className="text-xs font-bold text-gray-700 block mb-1">Confirm New Password</label>
                  <input
                    type="password"
                    required
                    value={confirmPass}
                    onChange={(e) => setConfirmPass(e.target.value)}
                    placeholder="Confirm new password"
                    className="w-full bg-gray-50 border border-gray-200 p-3 rounded-xl text-xs font-medium text-slate-900 focus:outline-none focus:border-emerald-600"
                  />
                </div>

                <button
                  type="submit"
                  className="bg-[#064e3b] hover:bg-green-700 text-white font-bold px-6 py-3 rounded-xl shadow-md transition-all text-xs"
                >
                  Update Password
                </button>
              </form>
            </div>
          </div>
        )}

        {/* Lead Detail Modal */}
        {selectedLead && (
          <LeadDetailModal
            lead={selectedLead}
            currentUser={currentUser}
            salesReps={salesReps}
            onClose={() => setSelectedLead(null)}
            onUpdateLead={handleUpdateLeadFromModal}
            onConvertToOffer={handleConvertToOffer}
          />
        )}

      </main>
    </div>
  );
}
